"""Figure "rebase" (Expose V): what merge-and-restart can reach (Thm V.3 and its corollaries 1, 2 and 4).

A port of site/js/fig-rebase.js (tabs A and B of the rebasing-reach explorer) and of checks 12q and 12t of
theory/framework_checks.py (butterfly hypergraph components, Lie closure of block-orthogonal factors).

Everything is float64 and seeded with the site's mulberry32 generator.

(a) Rank staircase (Thm V.3(a), Cor 1, Cor 2). W0 in R^{24x16} is injective with singular values 2 -> 0.5 evenly spaced.
    ReLoRA adds a fresh random rank-r product B_k A_k each cycle (B_k with N(0,1) entries, A_k with N(0, 1/n) entries);
    the rank of the accumulated update sum_k B_k A_k is measured by an SVD (tolerance 1e-9 sigma_1, floor 1e-12) and
    compared with min(K r, m, n). LoRA-XS with frames frozen at W0 updates U_r R_k V_r^T (R_k with N(0, 1/r^2)
    entries, the site's default update size): its accumulated update keeps rank r (idempotent, Cor 2).

(b) Block-orthogonal factors on n = 16 coordinates (Thm V.3(b), (c), Cor 4). Each factor family is a set of coordinate
    blocks I_j (block OFT: a fixed partition; BOFT with block size b and m' butterfly factors: level l pairs half-block
    c with c XOR 2^l; Givens: planes {i, j}). Union-find gives the components C of the hypergraph, and
    dim Lie<so(I_j)> = sum_C C(|C|, 2) (Thm V.3(c)). Two independent measurements confirm each value:
      Lie closure    the dimension of the Lie algebra generated by the plane rotations spanning the so(I_j),
                     by repeated brackets (as in check 12t of framework_checks.py);
      reach          dim R_K, the rank of the right-trivialised Jacobian of the K-cycle product of exact-Cayley factors
                     F = (I + Q)(I - Q)^{-1} at a random point (the site's jacDims), for K = 1..16 merge cycles.
    The bars show dim R_1 (one cycle) and dim R_16 = dim Lie<so(I_j)> against dim so(16) = 120.

Run from paper/figures/src:  python3 fig_rebase.py
"""
import math
import warnings

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Rectangle

from style import apply_style, C, W1, save

M32 = 0xFFFFFFFF
# NumPy 2.0 with Apple Accelerate raises spurious floating-point warnings inside matmul even when every product is
# exact and finite; silence only those (the asserts below check every result)
warnings.filterwarnings('ignore', message='.*encountered in matmul', category=RuntimeWarning)


class Rng:
    """The site's seeded generator (site/js/core.js: Atlas.rng, mulberry32 + Box-Muller)."""

    def __init__(self, seed):
        self.a = (seed & M32) or 1

    def __call__(self):
        self.a = (self.a + 0x6D2B79F5) & M32
        a = self.a
        t = ((a ^ (a >> 15)) * (1 | a)) & M32
        t = ((t + (((t ^ (t >> 7)) * (61 | t)) & M32)) & M32) ^ t
        return ((t ^ (t >> 14)) & M32) / 4294967296

    def normal(self):
        u = 0.0
        while u == 0:
            u = self()
        v = 0.0
        while v == 0:
            v = self()
        return math.sqrt(-2 * math.log(u)) * math.cos(2 * math.pi * v)

    def randn(self, m, n, scale=1.0):
        """LA.randn: row-major draws."""
        return np.array([[self.normal() * scale for _ in range(n)] for _ in range(m)])


M, N = 24, 16
DIM_SO = N * (N - 1) // 2                       # 120
RTOL, ATOL = 1e-9, 1e-12
SIG = [2 - 1.5 * i / (N - 1) for i in range(N)]
UPD = 1.0                                       # LoRA-XS update size E||R_k||_F (the site's default)
KMAX = 8
RS = [3, 5]                                     # ReLoRA ranks shown
R_XS = 5                                        # LoRA-XS (frozen frame) rank shown
KB = 16                                         # merge cycles for the reach measurement


def rank(X):
    s = np.linalg.svd(X, compute_uv=False)
    tol = max(RTOL * s[0], ATOL)
    return int(np.sum(s > tol))


def orth_cols(m, n, rnd):
    """m x n with orthonormal columns (Gram-Schmidt twice), drawn column by column as on the site."""
    cols = []
    for _ in range(n):
        v = np.array([rnd.normal() for _ in range(m)])
        for _ in range(2):
            for c in cols:
                v -= (v @ c) * c
        cols.append(v / np.linalg.norm(v))
    return np.array(cols).T


def base():
    rnd = Rng(20261001)
    U, V = orth_cols(M, N, rnd), orth_cols(N, N, rnd)
    W0 = U @ np.diag(SIG) @ V.T
    return W0


# ---------------------------------------------------------------------------------------------------------------
# (a) additive rebasing
# ---------------------------------------------------------------------------------------------------------------
def run_a(W0, r, upd=UPD, seed=1, Kmax=KMAX):
    rA, rX = Rng(1000 + 31 * seed + r), Rng(5000 + 31 * seed + r)
    U, s, Vt = np.linalg.svd(W0, full_matrices=False)
    U0, V0 = U[:, :r], Vt[:r].T
    D, Df = np.zeros((M, N)), np.zeros((M, N))
    out = dict(r=r, relora=[0], bound=[0], xsF=[0])
    for k in range(1, Kmax + 1):
        B = rA.randn(M, r)
        A = rA.randn(r, N, 1 / math.sqrt(N))
        D = D + B @ A
        out['relora'].append(rank(D))
        out['bound'].append(min(k * r, M, N))
        R = rX.randn(r, r, upd / r)                 # E ||R_k||_F^2 = upd^2
        Df = Df + U0 @ R @ V0.T
        out['xsF'].append(rank(Df))
    out['Kstar'] = math.ceil(min(M, N) / r)
    return out


# ---------------------------------------------------------------------------------------------------------------
# (b) block-orthogonal factors
# ---------------------------------------------------------------------------------------------------------------
def contiguous(b):
    return [list(range(s, s + b)) for s in range(0, N, b)]


def butterfly_level(b, l):
    """BOFT factor at level l with block size b: half-blocks of size b/2, half-block c paired with c XOR 2^l."""
    hh, H = b // 2, N // (b // 2)
    out = []
    for c in range(H):
        c2 = c ^ (1 << l)
        if c < c2 < H:
            out.append(list(range(c * hh, c * hh + hh)) + list(range(c2 * hh, c2 * hh + hh)))
    return out


GIVENS7 = [[0, 1], [1, 5], [5, 6], [9, 10], [10, 14], [3, 12], [7, 8]]             # the site's default planes
GIVENS15 = GIVENS7 + [[6, 9], [2, 3], [4, 5], [8, 11], [12, 13], [14, 15], [11, 13], [10, 12]]   # a spanning tree

FAMILIES = [   # (group, parameter label, list of factors; each factor is a list of disjoint blocks)
    ('block OFT', r'$b=4$', [contiguous(4)]),
    ('block OFT', r'$b=8$', [contiguous(8)]),
    ('BOFT, $b=2$', r"$m′=2$", [butterfly_level(2, l) for l in range(2)]),
    ('BOFT, $b=2$', r"$m′=3$", [butterfly_level(2, l) for l in range(3)]),
    ('BOFT, $b=2$', r"$m′=4$, full depth", [butterfly_level(2, l) for l in range(4)]),
    ('Givens', '7 planes', [[p] for p in GIVENS7]),
    ('Givens', '15 planes, a tree', [[p] for p in GIVENS15]),
]


def components(factors):
    par = list(range(N))

    def find(x):
        while par[x] != x:
            par[x] = par[par[x]]
            x = par[x]
        return x
    for f in factors:
        for I in f:
            for t in I[1:]:
                a, c = find(I[0]), find(t)
                if a != c:
                    par[c] = a
    roots, lab, sizes = {}, [], []
    for i in range(N):
        rt = find(i)
        if rt not in roots:
            roots[rt] = len(sizes)
            sizes.append(0)
        lab.append(roots[rt])
        sizes[roots[rt]] += 1
    return dict(lab=lab, sizes=sizes, lie=sum(s * (s - 1) // 2 for s in sizes))


def generators(factors):
    """A basis of every so(I_j): the plane rotations L_ac = E_ac - E_ca for a < c in a block I_j."""
    out = []
    for f in factors:
        for I in f:
            for a in range(len(I)):
                for c in range(a + 1, len(I)):
                    L = np.zeros((N, N))
                    L[I[a], I[c]], L[I[c], I[a]] = 1.0, -1.0
                    out.append(L)
    return out


def lie_closure(gens, tol=1e-8):
    """Dimension of the Lie algebra generated by gens (check 12t of framework_checks.py): add brackets until closed."""
    basis = []

    def add(Mx):
        v = Mx.ravel()
        res = v - (np.array(basis).T @ (np.array(basis) @ v) if basis else 0)
        if np.linalg.norm(res) > tol * max(1.0, np.linalg.norm(v)):
            basis.append(res / np.linalg.norm(res))
            return True
        return False
    mats = [G for G in gens if add(G)]
    frontier = list(mats)
    while frontier:
        new = []
        for X in frontier:
            for Y in mats:
                Z = X @ Y - Y @ X
                if add(Z):
                    new.append(Z)
        mats += new
        frontier = new
    return len(basis)


def cayley(Q):
    I = np.eye(len(Q))
    return (I + Q) @ np.linalg.inv(I - Q)


def reach_dims(factors, seed=1, K=KB):
    """dim R_k, k = 1..K, for exact-Cayley factors (the site's jacDims, map = 'exact'). The right-trivialised tangent
    of (factors) -> F_1 ... F_P is spanned by T L_ac T^T, with T the product of the factors before F_j and L_ac the
    rotation generators of F_j's blocks (the Cayley map is a local diffeomorphism and T is orthogonal)."""
    rnd = Rng(4242 + seed)
    iu = np.triu_indices(N, 1)
    T = np.eye(N)
    vecs, dims = [], []
    for _ in range(K):
        for f in factors:
            for I in f:
                for a in range(len(I)):
                    for c in range(a + 1, len(I)):
                        X = np.outer(T[:, I[a]], T[:, I[c]])
                        vecs.append((X - X.T)[iu])
            Q = np.zeros((N, N))
            for I in f:                              # random skew generator on the factor's blocks (scale 0.3/sqrt b)
                sc = 0.3 / math.sqrt(len(I))
                for a in range(len(I)):
                    for c in range(a + 1, len(I)):
                        x = rnd.normal() * sc
                        Q[I[a], I[c]], Q[I[c], I[a]] = x, -x
            T = T @ cayley(Q)
        s = np.linalg.svd(np.array(vecs), compute_uv=False)
        dims.append(int(np.sum(s > 1e-8 * s[0])))
    return dims


def compute():
    W0 = base()
    s = np.linalg.svd(W0, compute_uv=False)
    print('W0: 24 x 16, rank %d, singular values %.3f .. %.3f' % (rank(W0), s[0], s[-1]))
    RA = {r: run_a(W0, r) for r in RS}
    if R_XS not in RA:
        RA[R_XS] = run_a(W0, R_XS)
    print('(a) rank of the accumulated update after K = 0..%d merge cycles' % KMAX)
    for r in sorted(RA):
        x = RA[r]
        print('   r = %d  ReLoRA %s  bound min(Kr, m, n) %s  K* = %d  | LoRA-XS frozen %s'
              % (r, x['relora'], x['bound'], x['Kstar'], x['xsF']))
        assert x['relora'] == x['bound'] and all(v == min(r, k * r) for k, v in enumerate(x['xsF']))

    print('(b) block-orthogonal factors on n = 16 coordinates')
    RB = []
    for grp, par, factors in FAMILIES:
        cp = components(factors)
        lc = lie_closure(generators(factors))
        dims = reach_dims(factors)
        ksat = next(k + 1 for k, d in enumerate(dims) if d == dims[-1])
        sizes = sorted(cp['sizes'], reverse=True)
        print('   %-12s %-22s components %-28s sum C(|C|,2) = %3d | Lie closure %3d | dim R_1 = %3d, dim R_16 = %3d '
              '(reached at K = %d)' % (grp.replace('$', ''), par.replace('$', ''), sizes, cp['lie'], lc, dims[0],
                                         dims[-1], ksat))
        assert lc == cp['lie'] == dims[-1]
        RB.append(dict(group=grp, par=par, factors=factors, comp=cp, lie=cp['lie'], closure=lc, dims=dims, ksat=ksat))
    return RA, RB


# ---------------------------------------------------------------------------------------------------------------
# drawing
# ---------------------------------------------------------------------------------------------------------------
def fit_width(fig, width, iters=5):
    """Rescale the figure so that its tight bounding box (what save() writes) is exactly `width` inches wide."""
    for _ in range(iters):
        fig.canvas.draw()
        bb = fig.get_tightbbox(fig.canvas.get_renderer())
        w = bb.width + 2 * plt.rcParams['savefig.pad_inches']
        if abs(w - width) < 1e-3:
            break
        fw, fh = fig.get_size_inches()
        fig.set_size_inches(fw * width / w, fh * width / w)


def panel_label(ax, s, x, y=1.0, transform=None):
    ax.text(x, y, s, transform=transform or ax.transAxes, fontsize=9, fontweight='medium', color=C['ink'],
            va='bottom', ha='left')


COMP_COLORS = [C['blue'], C['orange'], C['green'], C['vermillion'], C['sky'], C['purple'], C['yellow']]


def draw(RA, RB):
    import matplotlib.patheffects as pe
    halo = [pe.withStroke(linewidth=2.2, foreground='white')]
    apply_style()
    fig = plt.figure(figsize=(W1, 2.6))
    gs = fig.add_gridspec(1, 3, width_ratios=[1.12, 1.25, 0.56], wspace=0.05, left=0.06, right=0.99, bottom=0.15,
                          top=0.9)
    axA = fig.add_subplot(gs[0, 0])
    axH = fig.add_subplot(gs[0, 1])
    axR = fig.add_subplot(gs[0, 2], sharey=axH)

    # ---------------- (a) the rank staircase ----------------
    ax = axA
    K = np.arange(KMAX + 1)
    ax.axhline(N, color=C['ink3'], lw=0.7, ls=(0, (4, 2.5)), zorder=1)
    marks = {3: ('o', 3.6), 5: ('s', 3.2)}
    for r in RS:
        x = RA[r]
        ax.plot(K, np.array(K) * r, color=C['ink3'], lw=0.5, ls=(0, (1, 1.8)), zorder=1)          # the line K r
        ax.plot(K, x['bound'], color=C['rule'], lw=3.6, drawstyle='steps-post', solid_capstyle='butt', zorder=2)
        ax.plot(K, x['relora'], color=C['tide'], lw=1.1, drawstyle='steps-post', zorder=3)
        ax.plot(K[1:], x['relora'][1:], marks[r][0], ms=marks[r][1], mfc=C['tide'], mec='white', mew=0.5, zorder=4)
    xs = RA[R_XS]
    ax.plot(K, xs['xsF'], color=C['seal'], lw=1.1, drawstyle='steps-post', zorder=3)
    ax.plot(K[1:], xs['xsF'][1:], 'D', ms=2.8, mfc=C['seal'], mec='white', mew=0.5, zorder=4)
    for r in RS:
        ks = RA[r]['Kstar']
        ax.plot([ks, ks], [0, N], color=C['moss'], lw=0.7, ls=(0, (1.5, 1.5)), zorder=1)
        ax.text(ks + 0.1, 0.4, r'$K^*=%d$' % ks, color=C['moss'], fontsize=7, ha='left', va='bottom')
    ax.text(0.12, N + 0.4, r'$\min(m,n)=16$, full fine-tuning', color=C['ink2'], fontsize=7, ha='left',
            va='bottom', path_effects=halo, zorder=5)
    ax.text(0.12, 13.2, r'ReLoRA, $r=5$', color=C['tide'], fontsize=7, ha='left', va='center', path_effects=halo,
            zorder=5)
    ax.text(5.25, 10.6, r'ReLoRA, $r=3$', color=C['tide'], fontsize=7, ha='left', va='center', path_effects=halo,
            zorder=5)
    ax.text(KMAX + 0.1, 4.3, 'LoRA-XS, frozen frame,\n' + r'$r=5$', color=C['seal'], fontsize=7, ha='right',
            va='top', linespacing=1.05, path_effects=halo, zorder=5)
    ax.set_xlim(0, KMAX + 0.2)
    ax.set_ylim(0, N + 2.2)
    ax.set_xticks(range(0, KMAX + 1, 2))
    ax.set_yticks([0, 4, 8, 12, 16])
    ax.set_xlabel(r'merge cycles $K$', labelpad=1)
    ax.set_ylabel(r'$\mathrm{rank}\,\Delta W_K$', labelpad=1)
    panel_label(ax, '(a)', -0.17, 1.0)

    # ---------------- (b) hypergraph glyphs ----------------
    ax = axH
    nr = len(RB)
    LX = -12.6                                        # left edge of the label column, in dot units
    YT = -1.25                                        # top of the header row
    ax.set_xlim(LX, 15.5)
    ax.set_ylim(nr - 0.2, YT)
    ax.axis('off')
    prev = None
    for i, row in enumerate(RB):
        y0 = i + 0.2                                  # dots
        if row['group'] != prev:
            ax.text(LX, y0 - 0.05, row['group'], fontsize=7.5, color=C['ink'], ha='left', va='center')
            if prev is not None:
                ax.plot([0, 1], [i - 0.5, i - 0.5], color=C['rule'], lw=0.5, clip_on=False,
                        transform=ax.get_yaxis_transform())
                axR.plot([0, 116], [i - 0.5, i - 0.5], color=C['rule'], lw=0.5, clip_on=False)
        prev = row['group']
        ax.text(-0.9, y0 - 0.05, row['par'], fontsize=7, color=C['ink2'], ha='right', va='center')
        # hyperedges: pairs as arcs, larger blocks as brackets
        for f in row['factors']:
            for I in f:
                lo, hi = min(I), max(I)
                if len(I) == 2:
                    t = np.linspace(0, 1, 40)
                    hgt = 0.12 + 0.12 * math.log2(hi - lo)
                    ax.plot(lo + (hi - lo) * t, y0 - 0.1 - hgt * 4 * t * (1 - t), color=C['ink3'], lw=0.5, zorder=1)
                else:
                    yb = y0 - 0.4
                    ax.plot([lo, hi], [yb, yb], color=C['ink3'], lw=0.6, zorder=1)
                    for j in I:
                        ax.plot([j, j], [yb, y0 - 0.1], color=C['ink3'], lw=0.5, zorder=1)
        cp = row['comp']
        order = sorted(range(len(cp['sizes'])), key=lambda c: cp['lab'].index(c))
        big = [c for c in order if cp['sizes'][c] > 1]
        for j in range(N):
            c = cp['lab'][j]
            if cp['sizes'][c] == 1:
                ax.plot([j], [y0], 'o', ms=3.3, mfc='white', mec=C['ink3'], mew=0.6, zorder=3)
            else:
                ax.plot([j], [y0], 'o', ms=3.5, mfc=COMP_COLORS[big.index(c) % len(COMP_COLORS)], mec='white',
                        mew=0.4, zorder=3)
    ax.text(7.5, -0.82, 'factor blocks on 16 coordinates,\ndots coloured by component', fontsize=7, color=C['ink2'],
            ha='center', va='center', linespacing=1.05)
    panel_label(ax, '(b)', LX, YT, transform=ax.transData)

    # ---------------- (b) generated dimension against dim SO(16) ----------------
    ax = axR
    for i, row in enumerate(RB):
        y0 = i + 0.1
        full = row['lie'] == DIM_SO
        col = C['moss'] if full else C['tide']
        ax.add_patch(Rectangle((0, y0 - 0.21), row['lie'], 0.42, fc=col, alpha=0.32, lw=0, zorder=2))
        ax.add_patch(Rectangle((0, y0 - 0.21), row['dims'][0], 0.42, fc=col, lw=0, zorder=3))
        if full:
            ax.text(row['lie'] - 3, y0, str(row['lie']), fontsize=7, color=C['ink'], ha='right', va='center', zorder=4)
        else:
            ax.text(row['lie'] + 3, y0, str(row['lie']), fontsize=7, color=C['ink'], ha='left', va='center')
    ax.axvline(DIM_SO, color=C['ink2'], lw=0.7, ls=(0, (3, 2)), zorder=1)
    ax.text(DIM_SO + 5, 2.6, r'$\dim\,\mathrm{SO}(16)=120$', fontsize=7, color=C['ink2'], ha='left', va='center',
            rotation=90)
    ax.set_xlim(0, 140)
    ax.set_xticks([0, 60, 120])
    ax.set_xlabel('dimension', labelpad=1)
    ax.spines['left'].set_visible(False)
    ax.tick_params(axis='y', left=False, labelleft=False)
    ax.legend([Rectangle((0, 0), 1, 1, fc=C['tide'], lw=0), Rectangle((0, 0), 1, 1, fc=C['tide'], alpha=0.32, lw=0)],
              ['one cycle', 'merged'], loc='upper left', bbox_to_anchor=(0.0, 1.0), handlelength=1.0,
              handleheight=0.7, borderaxespad=0.0, labelspacing=0.15, handletextpad=0.4, fontsize=7)
    fit_width(fig, W1)
    return fig


if __name__ == '__main__':
    RA, RB = compute()
    fig = draw(RA, RB)
    print('wrote', save(fig, 'rebase'))
