#!/usr/bin/env python3
"""Generate the data-driven LaTeX tables and the arXiv ancillary files from the site data.

Outputs (paper/tables): counts.tex (macros), periodic.tex, catalogue.tex, arrows.tex, obstructions.tex
Outputs (paper/anc):    catalogue.csv, catalogue.json, arrows.csv, obstructions.csv, propositions.json, framework_checks.py, README.txt
"""
import csv, json, os, re, shutil, collections

HERE = os.path.dirname(os.path.abspath(__file__)); PAPER = os.path.dirname(HERE); ROOT = os.path.dirname(PAPER)
T = lambda *p: os.path.join(PAPER, 'tables', *p); A = lambda *p: os.path.join(PAPER, 'anc', *p)
src = open(os.path.join(ROOT, 'site', 'data', 'atlas-data.js')).read()
D = json.loads(src[src.index('{'):src.rstrip().rindex('}') + 1])
M = D['methods']; byid = {m['id']: m for m in M}
edges = json.load(open(os.path.join(ROOT, 'research', 'classified', 'edges.json')))

UNI = {'³': r'\textsuperscript{3}', '²': r'\textsuperscript{2}', '–': '--', '—': '---', '’': "'", '‘': '`', '“': '``', '”': "''",
       '×': r'$\times$', '≤': r'$\le$', '≥': r'$\ge$', '→': r'$\to$', 'α': r'$\alpha$', 'β': r'$\beta$', 'λ': r'$\lambda$',
       'μ': r'$\mu$', '∞': r'$\infty$', '·': r'$\cdot$', '⊗': r'$\otimes$', '√': r'$\surd$', 'ε': r'$\varepsilon$', 'θ': r'$\theta$',
       'Δ': r'$\Delta$', 'π': r'$\pi$', 'σ': r'$\sigma$', 'ρ': r'$\rho$', 'γ': r'$\gamma$', 'δ': r'$\delta$', 'ℓ': r'$\ell$',
       'Σ': r'$\Sigma$', 'Φ': r'$\Phi$', 'Ω': r'$\Omega$', '∘': r'$\circ$', '⊙': r'$\odot$', '∩': r'$\cap$', '\u00a0': '~', '\u2009': ' '}

def tx(s):
    """Plain text -> LaTeX (escape specials, map common unicode)."""
    s = str(s or '')
    s = s.replace('\\', r'\textbackslash{}')
    s = re.sub(r'\^([A-Za-z0-9])', '\x00\\1', s)    # a name such as "Spectral Adapter^R" carries a superscript
    for a, b in (('&', r'\&'), ('%', r'\%'), ('#', r'\#'), ('_', r'\_'), ('{', r'\{'), ('}', r'\}'), ('$', r'\$'), ('^', r'\^{}'), ('~', r'\~{}')):
        s = s.replace(a, b)
    s = re.sub('\x00(.)', r'\\textsuperscript{\1}', s)
    for a, b in UNI.items():
        s = s.replace(a, b)
    return s

def mathfix(s):
    """MathJax TeX -> LaTeX math (drop MathJax-only macros)."""
    s = str(s or '')
    s = s.replace(r'\lt', '<').replace(r'\gt', '>').replace(r'\unicode', '').replace(r'\bbox', '')
    s = re.sub(r'\\text\{([^{}]*)\}', lambda m: r'\text{' + m.group(1).replace('_', r'\_').replace('&', r'\&') + '}', s)
    for a, b in UNI.items():
        if b.startswith('$'):
            s = s.replace(a, b.strip('$') + ' ')
    return s

AX = ['kind', 'shape', 'base_point', 'gauge', 'covariance', 'merge', 'rebasing']
SHORT = {'GLxGL': r'GL$\times$GL', 'OxO': r'O$\times$O', 'GLxCO': r'GL$\times$CO', 'MonxGL': r'Mon$\times$GL', 'MonxMon': r'Mon$\times$Mon',
         'Pi': r'$\Pi$', 'GLxTorus': r'GL$\times$T', 'M1->': r'M1$\to$', 'Minf': r'M$\infty$', 'E0': r'E$^{0}$', 'F_T': r'F$_T$',
         'Cone*': r'Cone$^{*}$', 'nonlinear': 'nonlin.', 'idempotent': 'idemp.', 'schedule': 'sched.', 'unpointed': 'unpt.',
         'regular': 'regular', 'neutral': 'neutral', 'defect': 'defect', 'apex': 'apex'}
def cv(v):
    if v is None or v == '' or v == 'n/a': return '--'
    return SHORT.get(v, tx(v))

def cite(m):
    k = m.get('bibkey'); return r'\citealp{' + k + '}' if k else ''

counts = {
    'nMethods': len(M), 'nPapers': len(D['papers']), 'nHF': sum(1 for m in M if m.get('hf_peft')),
    'nCore': sum(1 for m in M if m.get('core')), 'nArrows': len(edges['edges']), 'nObstructions': len(edges.get('obstructions', [])),
    'nPropositions': len(D.get('propositions', [])), 'nBib': len(open(os.path.join(PAPER, 'bib', 'refs.bib')).read().split('\n@')) ,
}
with open(T('counts.tex'), 'w') as f:
    for k, v in counts.items():
        f.write('\\newcommand{\\%s}{%s}\n' % (k, f'{v:,}'.replace(',', '{,}')))

# ---------- periodic table (core methods): rows = table_row, columns = shape
ROWS = ['R-additive', 'R-action', 'R-Hadamard', 'R-selective', 'E', 'E0', 'B', 'P', 'F_T']
ROWNAME = {'R-additive': r'R, additive', 'R-action': r'R, action', 'R-Hadamard': r'R, Hadamard', 'R-selective': r'R, selective',
           'E': 'E (pointed ext.)', 'E0': r'E$^{0}$ (unpointed)', 'B': 'B (backward)', 'P': 'P (post hoc)', 'F_T': r'F$_T$ (family)'}
COLS = ['Lin', 'Cone', 'Cone*', 'Orb', 'Sat', 'Meet', 'Fun']
cells = collections.defaultdict(list)
for m in M:
    if not m.get('core'): continue
    r = m.get('table_row') or ''; c = m.get('table_col') or (m.get('coords') or {}).get('shape') or '--'
    if r not in ROWS: r = 'P' if (m.get('coords') or {}).get('kind') == 'P' else r
    cells[(r, c)].append(m)
with open(T('periodic.tex'), 'w') as f:
    f.write('% generated by tools/make_tables.py\n\\begingroup\\scriptsize\\setlength{\\tabcolsep}{3pt}\\renewcommand{\\arraystretch}{1.15}\n')
    f.write('\\begin{tabularx}{\\linewidth}{@{}>{\\raggedright\\arraybackslash}p{1.9cm}' + '>{\\raggedright\\arraybackslash}X' * len(COLS) + '@{}}\n\\toprule\\headrow\n')
    f.write('\\textbf{Kind} & ' + ' & '.join('\\textbf{' + SHORT.get(c, c) + '}' for c in COLS) + '\\\\\\midrule\n')
    for r in ROWS:
        row = [ROWNAME[r]]
        for c in COLS:
            names = sorted(cells.get((r, c), []), key=lambda m: m['name'].lower())
            row.append(', '.join(tx(m['name']) for m in names) if names else '\\textcolor{inkgray!70}{\\textperiodcentered}')
        f.write(' & '.join(row) + '\\\\\n')
    f.write('\\bottomrule\n\\end{tabularx}\\endgroup\n')

# ---------- full catalogue (longtable)
ORDER = {r: i for i, r in enumerate(ROWS)}
rows = sorted(M, key=lambda m: (ORDER.get(m.get('table_row') or '', 99), (m.get('name') or '').lower()))
with open(T('catalogue.tex'), 'w') as f:
    f.write('% generated by tools/make_tables.py\n\\begingroup\\scriptsize\\setlength{\\tabcolsep}{2.1pt}\\renewcommand{\\arraystretch}{1.08}\n')
    # the Reference column is wide enough for 'Farhadzadeh et al., 2025' on one line
    f.write('\\begin{longtable}{@{}>{\\raggedright\\arraybackslash}p{2.53cm}>{\\raggedright\\arraybackslash}p{3.2cm}r l l l l l l l l@{}}\n')
    head = '\\toprule\\headrow\\textbf{Method} & \\textbf{Reference} & \\textbf{Year} & \\textbf{Kind} & \\textbf{Shape} & \\textbf{Base pt.} & \\textbf{Gauge} & \\textbf{Covar.} & \\textbf{Merge} & \\textbf{Rebase} & \\textbf{HF}\\\\\\midrule\n'
    f.write('\\caption{The complete catalogue: every method with its seven coordinates (\\S\\ref{sec:atlas}). Core methods are marked $\\bullet$; HF marks methods available in Hugging Face PEFT at the pinned commit. ``--\'\' means the axis does not apply.}\\label{tab:catalogue}\\\\\n')
    # continuation pages repeat the head under a 'Table N, continued' line and end with 'continued on the next page',
    # as the hand-set long tables of the exposes do
    f.write(head + '\\endfirsthead\n\\multicolumn{11}{@{}l}{\\footnotesize\\itshape Table~\\ref{tab:catalogue}, continued}\\\\\n' + head + '\\endhead\n'
            '\\midrule\n\\multicolumn{11}{@{}r}{\\footnotesize\\itshape continued on the next page}\\\\\n\\endfoot\n\\bottomrule\\endlastfoot\n')
    last = None
    for m in rows:
        r = m.get('table_row') or ''
        if r != last:
            f.write('\\multicolumn{11}{@{}l}{\\sffamily\\bfseries\\color{tide}' + (ROWNAME.get(r, tx(r) or 'Other')) + '}\\\\[1pt]\n'); last = r
        co = m.get('coords') or {}
        f.write(' & '.join([('$\\bullet$\\,' if m.get('core') else '') + tx(m['name']), cite(m), str(m.get('year', '')),
                            *[cv(co.get(a)) for a in AX], '\\checkmark' if m.get('hf_peft') else '']) + '\\\\\n')
    f.write('\\end{longtable}\\endgroup\n')

# ---------- arrows (longtable) and obstructions
def nm(i): return tx(byid[i]['name']) if i in byid else tx(i)
with open(T('arrows.tex'), 'w') as f:
    f.write('% generated by tools/make_tables.py\n\\begingroup\\scriptsize\\setlength{\\tabcolsep}{3pt}\\renewcommand{\\arraystretch}{1.12}\n')
    f.write('\\begin{longtable}{@{}>{\\raggedright\\arraybackslash}p{2.4cm}>{\\raggedright\\arraybackslash}p{2.4cm}c>{\\raggedright\\arraybackslash}p{8.6cm}@{}}\n')
    head = '\\toprule\\headrow\\textbf{Source $M$} & \\textbf{Target $N$} & \\textbf{Rule} & \\textbf{Pointed map $h$ with $\\rho_N\\circ h=\\rho_M$}\\\\\\midrule\n'
    f.write('\\caption{Every recorded simulation arrow $M\\to N$ (rules A2--A5 of \\S\\ref{sec:atlas}), with its explicit map. Notes on the instances (rank, pointing) are in the ancillary file \\texttt{arrows.csv}.}\\label{tab:arrows}\\\\\n')
    # continuation pages repeat the head under a 'Table N, continued' line and end with 'continued on the next page',
    # as the hand-set long tables of the exposes do
    f.write(head + '\\endfirsthead\n\\multicolumn{4}{@{}l}{\\footnotesize\\itshape Table~\\ref{tab:arrows}, continued}\\\\\n' + head + '\\endhead\n'
            '\\midrule\n\\multicolumn{4}{@{}r}{\\footnotesize\\itshape continued on the next page}\\\\\n\\endfoot\n\\bottomrule\\endlastfoot\n')
    for e in sorted(edges['edges'], key=lambda e: (nm(e['source']).lower(), nm(e['target']).lower())):
        h = mathfix(e.get('h', '')).strip()
        f.write(f"{nm(e['source'])} & {nm(e['target'])} & {tx(e.get('rule',''))} & ${h}$\\\\\n" if h else f"{nm(e['source'])} & {nm(e['target'])} & {tx(e.get('rule',''))} & \\\\\n")
    f.write('\\end{longtable}\\endgroup\n')
oc = collections.Counter(o.get('test') for o in edges.get('obstructions', []))
with open(T('obstructions.tex'), 'w') as f:
    f.write('% generated by tools/make_tables.py\n\\begin{tabular}{@{}lrl@{}}\\toprule\\headrow\\textbf{Test} & \\textbf{Count} & \\textbf{What fails}\\\\\\midrule\n')
    for t, what in (('O1', 'an image invariant (Gram matrix, spectrum, row lines, zero pattern) or image inclusion'), ('O2', 'dimension or cut-rank'), ('O3', 'first-order image or base-point stratum')):
        f.write(f'{t} & {oc.get(t, 0)} & {what}\\\\\n')
    f.write('\\bottomrule\\end{tabular}\n')

# ---------- ancillary files
os.makedirs(A(), exist_ok=True)
FIELDS = ['id', 'name', 'full_name', 'paper_title', 'authors', 'year', 'venue', 'arxiv', 'url', 'code_url', 'hf_peft', 'hf_peft_config',
          'modification_kind', 'formula_latex', 'trainable_params', 'locus', 'structure', 'mergeable', 'mergeable_reason', 'identity_at_init',
          'key_idea', 'results_note', 'core', 'entry_type', 'table_row', 'table_col', 'categorical_reading', 'bibkey']
with open(A('catalogue.csv'), 'w', newline='') as f:
    w = csv.writer(f); w.writerow(FIELDS + AX)
    for m in M:
        co = m.get('coords') or {}
        w.writerow([m.get(k, '') for k in FIELDS] + [co.get(a, '') for a in AX])
json.dump({'methods': M, 'papers': D['papers'], 'axes': D['axes'], 'arrow_rules': D['arrow_rules']}, open(A('catalogue.json'), 'w'), ensure_ascii=False, indent=1)
with open(A('arrows.csv'), 'w', newline='') as f:
    w = csv.writer(f); w.writerow(['source', 'target', 'rule', 'h', 'note'])
    for e in edges['edges']: w.writerow([e.get(k, '') for k in ('source', 'target', 'rule', 'h', 'note')])
with open(A('obstructions.csv'), 'w', newline='') as f:
    w = csv.writer(f); w.writerow(['source', 'target', 'test', 'reason'])
    for o in edges.get('obstructions', []): w.writerow([o.get(k, '') for k in ('source', 'target', 'test', 'reason')])
shutil.copy(os.path.join(ROOT, 'theory', 'propositions.json'), A('propositions.json'))
shutil.copy(os.path.join(ROOT, 'theory', 'framework_checks.py'), A('framework_checks.py'))
open(A('README.txt'), 'w').write(
    'Ancillary files for "A Categorical Atlas of Parameter-Efficient Fine-Tuning: Cones, Orbits, and Gauges".\n'
    'catalogue.csv / catalogue.json  every catalogued PEFT method (%d) and paper (%d), verified metadata, formulas, seven coordinates.\n'
    'arrows.csv                      every recorded simulation arrow M -> N with its explicit map h and notes on the instance.\n'
    'obstructions.csv                every recorded obstruction with the failing test (O1-O3).\n'
    'propositions.json               every numbered result with statement, proof and review status.\n'
    'framework_checks.py             numerical checks behind the [Num] claims (python3 framework_checks.py; numpy).\n' % (len(M), len(D['papers'])))
print(counts, 'periodic cells', len(cells))
